### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by chantelanuit** [johannes-titz/mimosa#1]
Hello Johannes,

Thank you for this wonderful Mimosa GUI that I introduced in my stats courses. I just noticed that the http://www.mimosa.icu/example gives a 403 error (forbidden). Would you be able to correct it ?

Best regards, and thank you for your hard work !

Michael

**Comment by johannes-titz** [comment]
Hi Michael,

sorry for the inconvenience, I migrated my server and forgot to setup the example subdirectory. For now you can just use: https://www.mimosa.icu/?example=school

I will try to fix it tomorrow.

Note that the app on mimosa.icu is hosted through shinyapps.io, so it cannot support many students at the same time. If you have larger classes you can use: https://method.hsw.tu-chemnitz.de/app_direct/mimosa/

It will support around 100 concurrent connections. I will probably migrate mimosa.icu to this new server in the future.

Thank you for recommending my GUI in your courses and sorry again for the inconvenience!

**Comment by chantelanuit** [comment]
Hi Johannes, Thank you, very appreciated !

**Comment by johannes-titz** [comment]
The link to the example should work again. I am closing this.
